/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        'headline-xl': ['Newsreader'],
        'headline-lg': ['Newsreader'],
        'headline-md': ['Newsreader'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-xl': ['84px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e0c0af',
        'on-background': '#e5e2e1',
        primary: '#ffb68b',
        'primary-container': '#ff7a00',
        'primary-fixed': '#ffdbc8',
        'primary-fixed-dim': '#ffb68b',
        'on-primary': '#522300',
        'on-primary-container': '#5c2800',
        'on-primary-fixed': '#321200',
        'on-primary-fixed-variant': '#753400',
        'inverse-primary': '#994700',
        secondary: '#c0c1ff',
        'secondary-container': '#3131c0',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary': '#1000a9',
        'on-secondary-container': '#b0b2ff',
        'on-secondary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        tertiary: '#4fdbc8',
        'tertiary-container': '#03b4a2',
        'tertiary-fixed': '#71f8e4',
        'tertiary-fixed-dim': '#4fdbc8',
        'on-tertiary': '#003731',
        'on-tertiary-container': '#003f38',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary-fixed-variant': '#005048',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#a78b7c',
        'outline-variant': '#584235',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'surface-tint': '#ffb68b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      backgroundImage: {
        'gradient-accent': 'linear-gradient(135deg,#ff7a00 0%,#ff9a3c 100%)',
        'gradient-ripple': 'linear-gradient(90deg,transparent,#ff7a00,transparent)',
        'gradient-hero': 'radial-gradient(circle at 50% 50%,rgba(255,122,0,0.13),transparent 70%)',
      },
      boxShadow: {
        glow: '0 0 20px rgba(255,122,0,0.4)',
        'glow-lg': '0 0 30px rgba(255,122,0,0.6)',
        card: '0 20px 40px rgba(0,0,0,0.8)',
      },
      animation: {
        'fade-up': 'fadeUp 0.8s cubic-bezier(0.4,0,0.2,1) forwards',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'ripple-out': 'rippleOut 2s ease-out infinite',
      },
      keyframes: {
        fadeUp: { from: { opacity: '0', transform: 'translateY(32px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        rippleOut: { '0%': { transform: 'scale(1)', opacity: '0.6' }, '100%': { transform: 'scale(2.5)', opacity: '0' } },
      },
    },
  },
  plugins: [],
}
